
version: '3.8'
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - 5672:5672 #Commiunication between services 
      - 15672:15672 #Navigate to rabbitMq Portal
    volumes:
      - rabbitMqdata:/var/lib/rabbitmq
    hostname: rabbitmq
volumes:
  mongodbdata: 
  rabbitMqdata:
